services:
  - type: web
    name: scope-insurance-backend
    env: python
    buildCommand: pip install poetry && poetry install
    startCommand: poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.12.0
